### ISSUE TITLE
微博轻享版6.2.4不能去除信息流广告

### ISSUE THREAD

**Issue by huddao** [Xposed-Modules-Repo/com.trump.myxposed#1]
您好，想问下去除信息流广告是默认开启的吗，我在插件设置里没看到开关。插件中微博的暗黑模式和隐藏发布按钮功能可以生效，还需要怎样的设置才能去除信息流广告吗？谢谢

**Comment by wangyuan0217** [comment]
第一版是在6.1.7开发的；
最新的加了版本兼容（只兼容了6.1.7 和6.2.6）

去广告是默认开启(无开关)
